# Generated by Django 5.0.2 on 2024-03-19 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("galv", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="datacolumntype",
            name="delete_access_level",
            field=models.IntegerField(
                choices=[(4, "Team Admin"), (3, "Team Member")], default=3
            ),
        ),
        migrations.AddField(
            model_name="datacolumntype",
            name="edit_access_level",
            field=models.IntegerField(
                choices=[
                    (4, "Team Admin"),
                    (3, "Team Member"),
                    (2, "Lab Member"),
                    (1, "Registered User"),
                ],
                default=3,
            ),
        ),
        migrations.AddField(
            model_name="datacolumntype",
            name="read_access_level",
            field=models.IntegerField(
                choices=[
                    (4, "Team Admin"),
                    (3, "Team Member"),
                    (2, "Lab Member"),
                    (1, "Registered User"),
                    (0, "Anonymous"),
                ],
                default=2,
            ),
        ),
        migrations.AddField(
            model_name="datacolumntype",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_resources",
                to="galv.team",
            ),
        ),
        migrations.AddField(
            model_name="dataunit",
            name="delete_access_level",
            field=models.IntegerField(
                choices=[(4, "Team Admin"), (3, "Team Member")], default=3
            ),
        ),
        migrations.AddField(
            model_name="dataunit",
            name="edit_access_level",
            field=models.IntegerField(
                choices=[
                    (4, "Team Admin"),
                    (3, "Team Member"),
                    (2, "Lab Member"),
                    (1, "Registered User"),
                ],
                default=3,
            ),
        ),
        migrations.AddField(
            model_name="dataunit",
            name="read_access_level",
            field=models.IntegerField(
                choices=[
                    (4, "Team Admin"),
                    (3, "Team Member"),
                    (2, "Lab Member"),
                    (1, "Registered User"),
                    (0, "Anonymous"),
                ],
                default=2,
            ),
        ),
        migrations.AddField(
            model_name="dataunit",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_resources",
                to="galv.team",
            ),
        ),
        migrations.AlterField(
            model_name="arbitraryfile",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_resources",
                to="galv.team",
            ),
        ),
        migrations.AlterField(
            model_name="cell",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_resources",
                to="galv.team",
            ),
        ),
        migrations.AlterField(
            model_name="cellfamily",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_resources",
                to="galv.team",
            ),
        ),
        migrations.AlterField(
            model_name="cyclertest",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_resources",
                to="galv.team",
            ),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_resources",
                to="galv.team",
            ),
        ),
        migrations.AlterField(
            model_name="equipmentfamily",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_resources",
                to="galv.team",
            ),
        ),
        migrations.AlterField(
            model_name="experiment",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_resources",
                to="galv.team",
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_resources",
                to="galv.team",
            ),
        ),
        migrations.AlterField(
            model_name="schedulefamily",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_resources",
                to="galv.team",
            ),
        ),
        migrations.AlterField(
            model_name="validationschema",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_resources",
                to="galv.team",
            ),
        ),
    ]
