# Generated by Django 5.0.2 on 2024-04-08 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galv', '0008_alter_presigneddatafile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='observedfile',
            name='core_metadata',
            field=models.JSONField(help_text='Unparsed core metadata from the harvester', null=True),
        ),
    ]
