# Generated by Django 5.0.2 on 2024-04-09 13:53

import galv.fields
import galv.models.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galv', '0011_remove_observedfile_storage_urls_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parquetpartition',
            name='storage_class_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parquetpartition',
            name='parquet_file',
            field=galv.fields.ParquetPartitionFileField(blank=True, help_text='Parquet file', null=True, upload_to=''),
        ),
    ]
