# Generated by Django 5.0.2 on 2024-04-15 08:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("galv", "0016_observedfile_monitored_paths"),
    ]

    operations = [
        migrations.AddField(
            model_name="observedfile",
            name="summary",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
