# Generated by Django 5.0.2 on 2024-04-15 11:04

import django.db.models.deletion
import galv.models.utils
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galv', '0017_observedfile_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColumnMapping',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('uuid', galv.models.utils.UUIDFieldLD(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('delete_access_level', models.IntegerField(choices=[(4, 'Team Admin'), (3, 'Team Member')], default=3)),
                ('edit_access_level', models.IntegerField(choices=[(4, 'Team Admin'), (3, 'Team Member'), (2, 'Lab Member'), (1, 'Registered User')], default=3)),
                ('read_access_level', models.IntegerField(choices=[(4, 'Team Admin'), (3, 'Team Member'), (2, 'Lab Member'), (1, 'Registered User'), (0, 'Anonymous')], default=2)),
                ('name', models.TextField(unique=True)),
                ('map', models.JSONField(help_text='Mapping of column names to Column objects')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_resources', to='galv.team')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='observedfile',
            name='mapping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observed_files', to='galv.columnmapping'),
        ),
    ]
