# Generated by Django 4.2.13 on 2024-05-15 12:06

from django.db import migrations, models
import galv.fields


class Migration(migrations.Migration):
    dependencies = [
        ("galv", "0026_observedfile_png"),
    ]

    operations = [
        migrations.AddField(
            model_name="observedfile",
            name="storage_class_name",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="observedfile",
            name="png",
            field=galv.fields.LabDependentStorageFileField(
                blank=True,
                help_text="Preview image of the file",
                null=True,
                upload_to="",
            ),
        ),
    ]
