# Generated by Django 5.0.3 on 2024-06-04 14:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("galv", "0030_remove_cyclertest_file_cyclertest_files"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DataColumn",
        ),
    ]
