# Generated by Django 5.0.3 on 2024-06-05 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galv', '0032_remove_arbitraryfile_custom_properties_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arbitraryfile',
            name='is_public',
        ),
    ]
