# Generated by Django 5.0.3 on 2024-06-05 15:17

import galv.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("galv", "0033_remove_arbitraryfile_is_public"),
    ]

    operations = [
        migrations.AlterField(
            model_name="arbitraryfile",
            name="file",
            field=galv.fields.LabDependentStorageFileField(
                blank=True, help_text="File", null=True, upload_to=""
            ),
        ),
        migrations.AlterField(
            model_name="arbitraryfile",
            name="name",
            field=models.TextField(help_text="The name of the file"),
        ),
        migrations.AlterUniqueTogether(
            name="arbitraryfile",
            unique_together={("file", "team"), ("name", "team")},
        ),
    ]
