# Generated by Django 5.0.3 on 2024-06-11 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galv', '0036_alter_additionals3storagetype_access_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionals3storagetype',
            name='location',
            field=models.TextField(blank=True, default='galv', help_text='Directory within the S3 bucket to store files in'),
        ),
    ]
