# Generated by Django 5.0.3 on 2024-06-19 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("galv", "0040_rename_quota_additionals3storagetype_quota_bytes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="knoxauthtoken",
            name="user",
            field=models.ForeignKey(
                help_text="User to whom the token belongs",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="galv.userproxy",
            ),
        ),
    ]
