# Generated by Django 5.0.3 on 2024-06-26 06:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("galv", "0043_alter_datacolumntype_data_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="observedfile",
            name="state",
            field=models.TextField(
                choices=[
                    ("RETRY IMPORT", "Retry Import"),
                    ("IMPORT FAILED", "Import Failed"),
                    ("UNSTABLE", "Unstable"),
                    ("GROWING", "Growing"),
                    ("STABLE", "Stable"),
                    ("IMPORTING", "Importing"),
                    ("AWAITING MAP ASSIGNMENT", "Awaiting Map Assignment"),
                    ("MAP ASSIGNED", "Map Assigned"),
                    ("AWAITING STORAGE", "Awaiting Storage"),
                    ("IMPORTED", "Imported"),
                ],
                default="UNSTABLE",
                help_text="File status; autogenerated but can be manually set to RETRY IMPORT",
            ),
        ),
    ]
