# Generated by Django 5.0.3 on 2024-07-10 09:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("galv", "0044_alter_observedfile_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="additionals3storagetype",
            name="name",
            field=models.TextField(
                blank=True,
                help_text="Human-friendly identifier for the storage type",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="galvstoragetype",
            name="name",
            field=models.TextField(
                blank=True,
                help_text="Human-friendly identifier for the storage type",
                null=True,
            ),
        ),
    ]
