# Generated by Django 5.0.3 on 2024-10-09 07:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("galv", "0046_alter_observedfile_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monitoredpath",
            name="regex",
            field=models.TextField(
                blank=True,
                default=".*",
                help_text="\n    Python.re regular expression to filter files by,\n    applied to full file name starting from this Path's directory",
                null=True,
            ),
        ),
    ]
