# Generated by Django 5.0.3 on 2025-02-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("galv", "0047_alter_monitoredpath_regex"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bibliographicinfo",
            name="bibjson",
        ),
        migrations.AddField(
            model_name="bibliographicinfo",
            name="bib_json",
            field=models.JSONField(default=dict),
        ),
    ]
