# Generated by Django 5.0.3 on 2025-06-15 21:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("galv", "0048_remove_bibliographicinfo_bibjson_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="additionals3storagetype",
            name="location",
            field=models.TextField(
                default="/",
                help_text="Directory within the S3 bucket to store files in",
            ),
        ),
    ]
