# Generated by Django 5.0.3 on 2025-06-23 14:41

import galv.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("galv", "0050_remove_parquetpartition_add_zip_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="observedfile",
            name="bytes_required",
        ),
        migrations.RemoveField(
            model_name="observedfile",
            name="num_partitions",
        ),
        migrations.AddField(
            model_name="observedfile",
            name="png_size",
            field=models.PositiveBigIntegerField(default=100000),
        ),
        migrations.AddField(
            model_name="observedfile",
            name="zip_size",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="additionals3storagetype",
            name="quota_bytes",
            field=models.BigIntegerField(
                help_text="Maximum storage capacity in bytes. 0 is unlimited"
            ),
        ),
        migrations.AlterField(
            model_name="galvstoragetype",
            name="quota_bytes",
            field=models.BigIntegerField(
                help_text="Maximum storage capacity in bytes. 0 is unlimited"
            ),
        ),
        migrations.AlterField(
            model_name="monitoredpath",
            name="max_partition_line_count",
            field=models.PositiveIntegerField(
                default=1000000,
                help_text="Maximum number of lines per csv file. If your data are very wide, select a lower number. For data with < 50 columns or so, 1_000,000 is a good starting point because it's close to the maximum number of rows supported by Excel.",
            ),
        ),
        migrations.AlterField(
            model_name="observedfile",
            name="zip_file",
            field=galv.fields.LabDependentStorageFileField(
                blank=True,
                default=None,
                help_text="Zipped CSV data",
                null=True,
                upload_to="",
            ),
        ),
    ]
