name: API Clients
on:
  workflow_call:
    inputs:
      skip:
        type: boolean
        description: "Skip this workflow entirely. Used to allow dependencies even if this is not run."
        required: false
        default: false
      dry_run:
        type: boolean
        description: 'Publish to test registries only. Do not actually release the package.'
        required: false
        default: false
      version:
        type: string
        description: 'Base version to use for the NPM package'
        required: true
      version_clean:
        type: string
        description: 'Base (clean) version to use for the PyPI package'
        required: true
  workflow_dispatch:
    inputs:
      skip:
        type: boolean
        description: "Skip this workflow entirely. Used to allow dependencies even if this is not run."
        required: false
        default: false
      debug_enabled:
        type: boolean
        description: 'Run the build with debugging enabled'
        required: false
        default: false
      dry_run:
        type: boolean
        description: 'Publish to test registries only. Do not actually release the package.'
        required: false
        default: false
      version:
        type: string
        description: 'Base version to use for the NPM package'
        required: true
      version_clean:
        type: string
        description: 'Base (clean) version to use for the PyPI package'
        required: true

jobs:
  make-clients:
    if: ${{ !inputs.skip }}
    runs-on: ubuntu-latest
    permissions:
      packages: write
      id-token: write  # IMPORTANT: mandatory for trusted publishing
    environment:
      name: ${{ inputs.dry_run == 'true' && 'testpypi' || 'pypi' }}
      url: ${{ inputs.dry_run == 'true' && 'https://test.pypi.org/p/galv-client' || 'https://pypi.org/p/galv-client' }}
    steps:
      - uses: actions/checkout@v4

      - name: Make clients directory
        run: |
          mkdir clients

      - name: Retrieve OpenAPI spec artifacts
        uses: actions/download-artifact@v4
        with:
          name: spec
          path: .dev/spec

      # Enable debugging of manually-triggered workflows if the input option was provided
      - name: Debug
        uses: owenthereal/action-upterm@v1
        if: ${{ inputs.debug_enabled }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Specify openapi-generator version
        run: docker pull openapitools/openapi-generator-cli:v6.6.0

      - name: Determine Python package version
        run: |
          VERSION_CLEAN=${{ inputs.version_clean }}
          V=${VERSION_CLEAN#v}

          # Real releases always use the clean tag version
          if [[ "${{ inputs.dry_run }}" == "false" ]]; then
            echo "PYPI_VERSION=$V" >> $GITHUB_ENV
            exit 0
          fi

          # Get the list of currently published versions from the test repository
          PYTHON_VERSIONS=$(pip index versions --pre --index-url https://test.pypi.org/simple/ galv)
          while true; do
            if ! echo "$PYTHON_VERSIONS" | grep -qE "$V(,|\s|$)"; then
              break
            fi

            if [[ $V =~ dev[0-9]+$ ]]; then
              V=$(echo "$V" | awk -F'dev' '{$NF = $NF + 1;} 1' | sed 's/ /dev/g')
            else
              V="${V}.dev0"
            fi
          done
          echo "PYPI_VERSION=$V" >> $GITHUB_ENV

      - name: Determine NPM package version
        run: |
          VERSION=${{ inputs.version }}
          V=${VERSION#v}

          # Real releases always use the clean tag version
          if [[ "${{ inputs.dry_run }}" == "false" ]]; then
              echo "NPM_VERSION=$V" >> $GITHUB_ENV
              exit 0
          fi

          # Get the list of currently published versions
          NPM_VERSIONS=$(npm show @galv/galv versions --json)

          while true; do
            if ! echo "$NPM_VERSIONS" | jq -e --arg v "$V" 'index($v)' > /dev/null; then
              break
            fi

            if [[ $V =~ -?dev[0-9]+$ ]]; then
              V=$(echo "$V" | awk -F'dev' '{$NF = $NF + 1;} 1' | sed 's/ /dev/')
            else
              V="${V}-dev0"
            fi
          done
          echo "NPM_VERSION=$V" >> $GITHUB_ENV

      - name: Create python config using calculated version
        run: |
          echo '{"packageName": "galv", "packageVersion": "$PYPI_VERSION"}' >> python-config.json
          cat python-config.json

      - name: Create API client - python
        run: |
          JSON_FILE=$(ls .dev/spec/*.json)
          docker run --rm -v "${PWD}:/local" openapitools/openapi-generator-cli:v6.6.0 generate \
          -i "/local/$JSON_FILE" \
          -g python \
          -c /local/python-config.json \
          -o /local/clients/python

          # Copy LICENCE file to client directory
          sudo cp LICENCE clients/python/LICENCE

          tree clients/python

          # zip the client
          zip -r clients/galv-client-python.zip clients/python

      - name: Create API client - typescript-axios
        run: |
          # Create a config json file using EOF notation
          echo '{"useSingleRequestParameter": true}' >> typescript-axios-config.json
          JSON_FILE=$(ls .dev/spec/*.json)
          docker run --rm -v "${PWD}:/local" openapitools/openapi-generator-cli:v6.6.0 generate \
          -i "/local/$JSON_FILE" \
          -g typescript-axios \
          -c /local/typescript-axios-config.json \
          -o /local/clients/typescript-axios

          # Copy LICENCE file to client directory
          sudo cp LICENCE clients/typescript-axios/LICENCE

          # Create a package.json file using EOF notation
          cat << EOF | sudo tee -a clients/typescript-axios/package.json
          {
              "name": "@galv/galv",
              "version": "$NPM_VERSION",
              "description": "Galv API client using Typescript-Axios",
              "main": "index.ts",
              "scripts": {
                "test": "echo \"Error: no test specified\" && exit 1"
              },
              "keywords": [
                "galv",
                "galv-api",
                "galv-client",
                "typescript-axios"
              ],
              "author": "Battery Intelligence Lab",
              "license": "See LICENCE File",
              "dependencies": {
                "axios": "^0.21.1"
              }
          }
          EOF

          # zip the client
          zip -r clients/galv-client-typescript-axios.zip clients/typescript-axios

      - name: Setup publishing typescript client to packages
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Publish typescript client to packages ${{ inputs.dry_run == 'true' && '[dry_run]' || '' }}
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_PUBLISH_TOKEN }}
          package: "clients/typescript-axios"
          access: "public"
          dry_run: ${{ inputs.dry_run }}

      - name: Upload clients
        uses: actions/upload-artifact@v4
        with:
          name: clients
          path: clients/*.zip
          retention-days: 1

      - name: Upload python client code
        uses: actions/upload-artifact@v4
        with:
          name: python
          path: clients/python
          retention-days: 1

      - name: Build distribution 📦
        run: |
          cd /local/clients/python
          python setup.py sdist bdist_wheel

      - name: Publish distribution 📦 to PyPI ${{ inputs.dry_run == 'true' && '[dry_run]' || '' }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: ${{ inputs.dry_run == 'true' && 'https://test.pypi.org/legacy/' || 'https://upload.pypi.org/legacy/' }}
          packages-dir: /local/clients/python

  rubber-stamp:
    if: ${{ inputs.skip }}
    runs-on: ubuntu-latest
    steps:
      - name: Report success to downstream jobs
        run: echo "Success"
