name: Run workflows

on:
  push:
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with debugging enabled'
        required: false
        default: false
      allow_breaking_changes:
        type: boolean
        description: 'Ignore breaking change failure in OpenAPI spec check.'
        required: false
        default: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  get-version:
    # Determine the version from the tag or branch name.
    # Determine the previous version from the tags.
    # Determine the previous major version from the tags.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract version
        id: current_version
        run: |
          # Extract release version from settings
          API_VERSION=$(cat backend_django/config/settings_base.py | grep "API_VERSION =" | cut -d'"' -f2)
          # Assert version is valid semver
          if ! [[ "$API_VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
              echo "API version v$API_VERSION is not valid clean semver"
              echo "Please check the API_VERSION in settings_base.py matches semver e.g. 1.2.3"
              exit 1
          fi

          echo "API_VERSION=v$API_VERSION" >> $GITHUB_ENV

          if [[ "${{ github.ref_type }}" == "tag" ]]; then
                IS_TAG=true
          else
                IS_TAG=false
          fi
          echo "IS_TAG=$IS_TAG" >> $GITHUB_ENV

          # Determine the tag/branch name
          if [[ $IS_TAG -gt 0 ]]; then
              REF_NAME=${GITHUB_REF#refs/tags/}
          else
              REF_NAME=${GITHUB_REF#refs/heads/}
          fi

          echo "REF_NAME=$REF_NAME"

          # Determine the version from the tag/branch name
          if ! [[ "$REF_NAME" =~ ^v[0-9]+\.[0-9]+\.[0-9]+(-.+)?$ ]]; then
              echo "Ref $REF_NAME is not valid semver. Using API_VERSION v$API_VERSION"
              echo "VERSION=v$API_VERSION" >> $GITHUB_ENV
              echo "VERSION_CLEAN=v$API_VERSION" >> $GITHUB_ENV
              echo "VERSION_SUFFIX=" >> $GITHUB_ENV
          else
              VERSION_CLEAN=$(echo $REF_NAME | grep -oP '^v[0-9]+\.[0-9]+\.[0-9]+' || true)
              VERSION_SUFFIX=$(echo $REF_NAME | grep -oP '(?<=-).*$' || true)
              # if we're not on a tag and we have a clean version, halt the workflow
              if [[ $IS_TAG -eq 0 && "$REF_NAME" == "$VERSION_CLEAN" ]]; then
                  echo "This branch has a clean version tag. Do not use clean version tags on branches."
                  echo "Use a different branch name, e.g. $VERSION_CLEAN-dev."
                  echo "When you are ready to release a new version, create a tag."
                  exit 1
              fi

              echo "VERSION=$REF_NAME" >> $GITHUB_ENV
              echo "VERSION_CLEAN=$VERSION_CLEAN" >> $GITHUB_ENV
              echo "VERSION_SUFFIX=$VERSION_SUFFIX" >> $GITHUB_ENV
          fi

          # Release versions are clean semver
          echo "IS_RELEASE=$(($IS_TAG && "$REF_NAME" == "$VERSION_CLEAN"))" >> $GITHUB_ENV

          # Ending in -rc# means it is a release candidate and should be staged
          if [[ "$REF_NAME" =~ \-rc[0-9]+$ ]]; then
            echo "IS_STAGE=false" >> $GITHUB_ENV
          else
            echo "IS_STAGE=true" >> $GITHUB_ENV
          fi

          echo "Set env vars:"
          cat $GITHUB_ENV

      - name: Check version
        run: |
          echo "Check version $VERSION vs API_VERSION $API_VERSION"
          if ! [[ "$VERSION_CLEAN" == "$API_VERSION" ]]; then
              echo "API_VERSION and VERSION do not match. This is probably a mistake."
              echo "API_VERSION=v$API_VERSION"
              echo "VERSION=$VERSION_CLEAN => CLEAN_VERSION=$VERSION_CLEAN"
              exit 1
          fi
          echo "OK"

      # Enable debugging of manually-triggered workflows if the input option was provided
      - name: Debug
        uses: owenthereal/action-upterm@v1
        if: github.event_name == 'workflow_dispatch' && inputs.debug_enabled == 'true'

      - name: List previous versions
        id: create_tag_list
        run: |
          # Get a list of all repository tags and branches
          git fetch --tags --force --quiet

          # Save tag list to a temporary file
          git tag --list > tags.txt
          # Save clean tags
          (cat tags.txt | grep -oE '^v[0-9]+\.[0-9]+\.[0-9]+$' > clean_tags.txt) || true
          cat clean_tags.txt

      - name: Search for previous version tag
        # The previous version meets the following criteria:
        # 1. It is a clean version (no suffix)
        # 2. Its numerical part is less than the current version
        # 3. Its numerical part is the highest among all tags that meet the previous criteria
        # The previous major version is as above, but the major version is less than the current major version
        id: previous_versions
        run: |
          # Get the previous tag
          python ./.github/workflows/scripts/find_prev_tag.py
          # Should have set
          # PREVIOUS_VERSION
          # PREVIOUS_MAJOR_VERSION
          # IS_LATEST
          if [[ "$PREVIOUS_VERSION" == "$PREVIOUS_MAJOR_VERSION" ]]; then
            echo "IS_MAJOR_VERSION=true" >> $GITHUB_ENV
          else
            echo "IS_MAJOR_VERSION=false" >> $GITHUB_ENV
          fi
          echo "Set env vars:"
          cat $GITHUB_ENV

      - name: Check content changes
        id: check_content_changes
        run: |
          # Check if `docs` directory has changed using git diff vs the previous version
          git diff --name-only $PREVIOUS_VERSION > diff.txt
          if [[ -z $(cat diff.txt | grep ^docs) ]]; then
              echo "No changes to docs directory"
              echo "DOCS_CHANGED=false" >> $GITHUB_ENV
          else
              echo "Changes to docs directory detected"
              echo "DOCS_CHANGED=true" >> $GITHUB_ENV
          fi

          # Check if `backend_django` directory has changed using git diff vs the previous version
          if [[ -z $(cat diff.txt | grep ^backend_django) ]]; then
              if [[ -z $(cat diff.txt | grep -v -E '^(\.gitignore|\.pre-commit-config.yaml|LICENCE|README\.md)$' | grep -E ^[^/]+$) ]]; then
                  echo "No changes to settings_base.py or root directory files"
                  echo "(.gitignore, .pre-commit-config.yaml, LICENCE, README.md are ignored)"
                  echo "BACKEND_CHANGED=false" >> $GITHUB_ENV
              else
                  echo "Changes to root directory files detected"
                  echo "(.gitignore, .pre-commit-config.yaml, LICENCE, README.md are ignored)"
                  echo "BACKEND_CHANGED=true" >> $GITHUB_ENV
              fi
          else
              echo "Changes to backend_django directory detected"
              echo "BACKEND_CHANGED=true" >> $GITHUB_ENV
          fi

          # Check if the demo instance workflow has been changed
          if [[ -z $(git diff $PREVIOUS_VERSION -- .github/workflows/demo.yml | grep DEMO_BACKEND_VERSION) ]]; then
              echo "No changes to DEMO_BACKEND_VERSION detected"
              echo "DEMO_UPDATE=false" >> $GITHUB_ENV
          else
              echo "Changes to DEMO_BACKEND_VERSION detected"
              echo "DEMO_UPDATE=true" >> $GITHUB_ENV
          fi

      - name: Setup docker-compose for OpenAPI spec check
        if: env.BACKEND_CHANGED == 'true'
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
          mkdir -p .dev/spec
          sudo chmod 777 .dev/spec
          touch .env.secret

      - name: Check OpenAPI Spec changes
        if: env.BACKEND_CHANGED == 'true'
        id: check_openapi_changes
        run: |
          # Generate the spec for this version
          # using x rather than a number means it appears later and gets picked up by `tail -n 1` in docker-compose check_spec
          docker-compose run \
            --rm \
            -e AWS_SECRET_ACCESS_KEY="not_set" \
            --entrypoint "/bin/bash -c" \
            app \
            "python manage.py spectacular --fail-on-warn --validate --format openapi-json >> /spec/openapi-x.json"
          # Copy spec for upload
          cp .dev/spec/openapi-x.json .dev/spec/openapi-${{ env.VERSION_CLEAN }}.json

          sudo chmod 777 .dev/spec/*
          # If previous version tag is empty, skip this step
          if [ -z "${{ env.PREVIOUS_VERSION }}" ]; then
              echo "No previous version tag found. This is probably the first version. Skipping spec check."
              exit 0
          fi
          wget -O .dev/spec/openapi-${{ env.PREVIOUS_VERSION }}.json https://github.com/galv-team/galv-backend/releases/download/${{ needs.version.outputs.prev-clean-version }}/openapi-${{ needs.version.outputs.prev-clean-version }}.json || true
          # Check whether we downloaded a file (i.e. whether that file has a size greater than 0)
          if [ ! -s .dev/spec/openapi-${{ env.PREVIOUS_VERSION }}.json ]; then
              echo "Failed to download spec for previous version: ${{ env.PREVIOUS_VERSION }}."
              echo "This can happen if something went wrong in publishing the previous version."
              echo "Generating spec from scratch..."
              echo "Checking out previous version tag: ${{ env.PREVIOUS_VERSION }}"
              git fetch --tags
              git checkout ${{ env.PREVIOUS_VERSION }}
              echo "Generating spec for previous version: ${{ env.PREVIOUS_VERSION }}"
              docker-compose run --rm -e AWS_SECRET_ACCESS_KEY="not_set" --entrypoint "/bin/bash -c" app "python manage.py spectacular --format openapi-json >> /spec/openapi-x.json"
              cp .dev/spec/openapi-x.json .dev/spec/openapi-${{ env.PREVIOUS_VERSION }}.json
              echo "Success. Switching to workflow branch."
              git checkout -
              echo "Spec generated. First 10 lines:"
          else
            echo "Downloaded spec for previous version: ${{ env.PREVIOUS_VERSION }}. First 10 lines:"
          fi
          head -n 10 .dev/spec/openapi-${{ env.PREVIOUS_VERSION }}.json
          echo "---------"
          echo "Check spec against previous version: ${{ env.PREVIOUS_VERSION }}"
          if [[ "${{ env.IS_MAJOR_VERSION }}" == "true" || "${{ inputs.allow_breaking_changes }}" == "true" ]]; then
            sudo docker-compose run --rm -e REMOTE_SPEC_SOURCE=/spec/openapi-${{ env.PREVIOUS_VERSION }}.json check_spec || true
          else
            sudo docker-compose run --rm -e REMOTE_SPEC_SOURCE=/spec/openapi-${{ env.PREVIOUS_VERSION }}.json check_spec
          fi
          ls -l .dev/spec
          echo ".dev/spec/diff.md:"
          cat .dev/spec/diff.md
          API_CHANGES=$(jq '.different' .dev/spec/diff.json)
          BREAKING_API_CHANGES=$(jq '.incompatible' .dev/spec/diff.json)
          echo "API_CHANGES=$API_CHANGES" >> $GITHUB_ENV
          echo "BREAKING_API_CHANGES=$BREAKING_API_CHANGES" >> $GITHUB_ENV
          echo "Set env vars:"
          cat $GITHUB_ENV

      - name: Run tests
        if: inputs.run_tests == 'true' || env.BACKEND_CHANGED == 'true'
        uses: ./.github/workflows/ci-tests.yml

      - name: Build and publish docs
        if: env.DOCS_CHANGED == 'true'
        uses: ./.github/workflows/docs.yml
        with:
          dry_run: ${{ !env.IS_RELEASE }}

      - name: Upload OpenAPI spec
        if: env.API_CHANGES == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: spec
          path: .dev/spec/openapi-${{ env.VERSION_CLEAN }}.json
          retention-days: 1

      - name: Upload OpenAPI diff.md
        if: env.API_CHANGES == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: diff
          path: .dev/spec/diff.md
          retention-days: 1

      - name: Build and publish API clients
        if: env.API_CHANGES == 'true'
        uses: ./.github/workflows/api-clients.yml
        with:
          dry_run: ${{ env.IS_RELEASE == 'false' }}
          base_version: ${{ env.VERSION_CLEAN }}

      - name: Build and publish Docker images
        if: env.BACKEND_CHANGED == 'true'
        uses: ./.github/workflows/docker-image.yml
        with:
          dry_run: ${{ env.IS_RELEASE == 'false' }}

      - name: Issue release
        if: env.IS_RELEASE == 'true'
        uses: ./.github/workflows/issue-release.yml

      - name: Update Staging instance
        if: env.IS_STAGE == 'true'
        uses: ./.github/workflows/update-staging.yml

      - name: Update demo instance
        if: env.DEMO_UPDATE == 'true'
        uses: ./.github/workflows/update-demo.yml
