# Every week, we destroy the Fly.io demo app and recreate it.
# Only the backend and database are destroyed; the frontend is updated separately.
name: Demo
on:
  schedule:
    # every week
    - cron: '42 0 * * 1'
  workflow_dispatch:
  push:
    branches:
      - demo
      - demo-*

permissions:
  packages: read

jobs:
  recreate-fly-demo:
    runs-on: ubuntu-latest
    concurrency: demo-group
    env:
      DEMO_BACKEND_VERSION: "v2.4.2"
      FRONTEND_URL: "https://galv-demo.fly.dev"
      FLY_DEMO_NAME: "galv-demo-backend"
      FLY_DEMO_DB_NAME: "galv-demo-db"
      FLY_ORG: "oxrse"
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Destroy Existing apps
        run: |
          # Search apps list for existing services
          flyctl apps list --org $FLY_ORG > apps.txt
          cat apps.txt
          # Check if the app exists with grep
          if grep -q $FLY_DEMO_NAME apps.txt; then
              echo "Destroying app $FLY_DEMO_NAME"
              flyctl apps destroy $FLY_DEMO_NAME --yes
          else
              echo "App $FLY_DEMO_NAME does not exist - skipping destroy step"
          fi
          # Check if the database exists
          if grep -q $FLY_DEMO_DB_NAME apps.txt; then
              echo "Destroying app $FLY_DEMO_DB_NAME"
              flyctl apps destroy $FLY_DEMO_DB_NAME --yes
          else
              echo "App $FLY_DEMO_DB_NAME does not exist - skipping destroy step"
          fi
      # Until we can reliably link the backend to the DB, we'll create them separately
      - name: Create DB
        run: |
          echo "Creating app $FLY_DEMO_DB_NAME"
          flyctl postgres create \
            --name $FLY_DEMO_DB_NAME \
            --org $FLY_ORG \
            --region lhr \
            --volume-size 2 \
            --vm-size shared-cpu-1x \
            --initial-cluster-size 1

      - name: Create Demo Backend
        run: |
          echo "Creating app $FLY_DEMO_NAME"
          flyctl apps create \
            --name $FLY_DEMO_NAME \
            --org $FLY_ORG

      - name: Connect DB to Backend
        run: |
          echo "Connecting $FLY_DEMO_DB_NAME to $FLY_DEMO_NAME"
          flyctl postgres attach $FLY_DEMO_DB_NAME \
            --config ./fly.demo.toml \
            --app $FLY_DEMO_NAME \
            --yes

      - name: Deploy Demo Backend
        run: |
          echo "Deploying app $FLY_DEMO_NAME"
          flyctl deploy \
            --app $FLY_DEMO_NAME \
            --config ./fly.demo.toml \
            --image ghcr.io/galv-team/galv-backend:$DEMO_BACKEND_VERSION \
            --env VIRTUAL_HOST=$FLY_DEMO_NAME.fly.dev \
            --env FRONTEND_VIRTUAL_HOST=$FRONTEND_URL \
            --remote-only \
            --yes
