# When we want to deploy a demo release, to check migrations and other things, we run this workflow.
name: Demo Release
on:
  workflow_dispatch:
    inputs:
      backend_version:
        type: string
        description: "The version of the backend to deploy."
        required: true
      cdk_repo_version:
        type: string
        description: "The ref/tag of the CDK repository to use for the deployment"
        required: false
        default: "main"
  workflow_call:
    inputs:
      backend_version:
        type: string
        description: "The version of the backend to deploy."
        required: true
  push:
    branches:
      - "noci/fix/demo"

permissions:
  packages: read
  contents: read
  id-token: write  # Needed for AWS authentication

jobs:
  recreate-demo:
    if: github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    concurrency: demo-group
    env:
      PROJECT_NAME: galv-demo
      DJANGO_SECRET_KEY: ${{ secrets.DJANGO_DEMO_SECRET_KEY }}
      DJANGO_SUPERUSER_PASSWORD: ${{ secrets.DJANGO_DEMO_SUPERUSER_PASSWORD }}
      DJANGO_EMAIL_HOST_PASSWORD: ${{ secrets.DJANGO_DEMO_EMAIL_HOST_PASSWORD }}
      DJANGO_USER_ACTIVATION_OVERRIDE_ADDRESSES: ${{ secrets.STAGE_DJANGO_USER_ACTIVATION_OVERRIDE_ADDRESSES }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials from vars
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.CDK_IAM_ROLE_ARN }}
          role-session-name: ${{ github.run_id }}
          aws-region: eu-west-2

      - name: Install AWS CDK
        run: |
          npm install -g aws-cdk@^=2.1018.0
          cdk --version

      - name: Checkout CDK repository
        uses: actions/checkout@v4
        with:
          repository: galv-team/galv-aws-cdk
          ref: ${{ inputs.cdk_repo_version || 'main' }}
          path: cdk

      - name: Install CDK dependencies
        run: |
          cd cdk
          pip install .

      - name: Rewrite cdk.json
        run: |
          BACKEND_REF="${{ inputs.backend_version }}"
          if [[ "$BACKEND_REF" == "noci/fix/demo" ]]; then
              BACKEND_REF="latest"
          fi
          cat > cdk/cdk.json <<EOF
          {
            "app": "python app.py",
            "context": {
              "name": "${{ env.PROJECT_NAME }}",
              "mailFromDomain": "${{ vars.CDK_CTX_DOMAIN_NAME }}",
              "mailFromUser": "${{ env.PROJECT_NAME }}-no-reply",
              "projectNameTag": "${{ env.PROJECT_NAME }}",
              "backendVersion": "$BACKEND_REF",
              "frontendVersion": "latest",
              "isProduction": true,
              "removalProtection": false,
              "frontendEnvironment": {},
              "backendEnvironment": {
                "DJANGO_SUPERUSER_USERNAME": "admin",
                "DJANGO_LOG_LEVEL": "DEBUG",
                "DJANGO_LOG_LEVEL_CORE": "DEBUG",
                "DJANGO_DEBUG": "True",
                "DJANGO_USER_ACTIVATION_OVERRIDE_ADDRESSES": "",
                "DJANGO_USER_ACTIVATION_TOKEN_EXPIRY_S": ""
              },
              "frontendSecretsName": "galv-frontend-secrets",
              "frontendSecretsKeys": [],
              "backendSecretsName": "galv-backend-secrets",
              "backendSecretsKeys": [],
              "smtpSecretName": "",
              "monitorIntervalMinutes": 5,
              "frontendSubdomain": "${{ env.PROJECT_NAME }}",
              "backendSubdomain": "${{ env.PROJECT_NAME }}-api",
              "domainName": "${{ vars.CDK_CTX_DOMAIN_NAME }}",
              "isRoute53Domain": true,
              "enableContainerInsights": null
            }
          }
          EOF

      - name: Destroy demo backend
        run: |
          cd cdk
          cdk destroy \
            --force \
            galv-demo-BackendStack

      - name: Deploy demo backend
        run: |
          cd cdk
          BACKEND_REF="${{ inputs.backend_version }}"
          if [[ "$BACKEND_REF" == "noci/fix/demo" ]]; then
              BACKEND_REF="latest"
          fi
          cdk deploy \
            --require-approval never \
            --context backendVersion=$BACKEND_REF \
            --all #galv-demo-BackendStack

      - name: Get backend healthcheck content
        run: |
          curl -sS -o healthcheck.json \
            "https://${{ env.PROJECT_NAME }}-api.${{ vars.CDK_CTX_DOMAIN_NAME }}/health/"
          cat healthcheck.json

      - name: Check healthcheck status ok
        run: |
          if ! jq -e '.status == "ok"' healthcheck.json; then
              echo "Backend healthcheck failed: $(jq -r '.status' healthcheck.json)"
              exit 1
          fi
