# When we want to deploy a stage release, to check migrations and other things, we run this workflow.
# At the very least, it runs on any tag that ends -rc\d+
# It will do the following:
# 1. Destroy any existing stage backend and database.
# 2. Create a fork of the BIL production database
# (3. Rewrite all s3 bucket pointers in the stage database to point to the stage bucket)
# 4. Deploy the stage backend using the :latest image
# 5. Deploy the stage backend using the target image, which will run migrations etc.
name: Stage Release
on:
  workflow_dispatch:
    inputs:
      cdk_repo_version:
        type: string
        description: "The ref/tag of the CDK repository to use for the deployment"
        required: false
        default: "main"
      min_compatible_version:
        type: string
        description: "The minimum version of the backend to use for checking compatibility."
        required: false
        default: ""
  workflow_call:
    inputs:
      min_compatible_version:
        type: string
        description: "The minimum version of the backend to use for checking compatibility."
        required: false
        default: ""
  push:
    branches:
      - "fix/deployments"

permissions:
  packages: read
  contents: read
  id-token: write  # Needed for AWS authentication

jobs:
  recreate-fly-stage:
    if: github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    concurrency: staging-group
    env:
      PROJECT_NAME: galv-stage
      DJANGO_SECRET_KEY: ${{ secrets.DJANGO_DEMO_SECRET_KEY }}
      DJANGO_SUPERUSER_PASSWORD: ${{ secrets.DJANGO_DEMO_SUPERUSER_PASSWORD }}
      DJANGO_EMAIL_HOST_PASSWORD: ${{ secrets.DJANGO_DEMO_EMAIL_HOST_PASSWORD }}
      DJANGO_USER_ACTIVATION_OVERRIDE_ADDRESSES: ${{ secrets.STAGE_DJANGO_USER_ACTIVATION_OVERRIDE_ADDRESSES }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials from vars
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.CDK_IAM_ROLE_ARN }}
          role-session-name: ${{ github.run_id }}
          aws-region: eu-west-2

      - name: Install AWS CDK
        run: |
          npm install -g aws-cdk@2.107.0
          cdk --version

      - name: Checkout CDK repository
        uses: actions/checkout@v4
        with:
          repository: galv-team/galv-aws-cdk
          ref: ${{ inputs.cdk_repo_version || 'main' }}
          path: cdk

      - name: Install CDK dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r cdk/requirements.txt

      - name: Rewrite cdk.json
        run: |
          cat > cdk/cdk.json <<EOF
          {
            "app": "python app.py",
            "context": {
              "name": "${{ env.PROJECT_NAME }}",
              "mailFromDomain": "${{ vars.CDK_CTX_DOMAIN_NAME }}",
              "mailFromUser": "${{ env.PROJECT_NAME }}-no-reply",
              "projectNameTag": "${{ env.PROJECT_NAME }}",
              "backendVersion": "${{ github.ref_name }}",
              "frontendVersion": "latest",
              "isProduction": true,
              "frontendEnvironment": {},
              "backendEnvironment": {
                "DJANGO_SUPERUSER_USERNAME": "admin",
                "DJANGO_LOG_LEVEL": "DEBUG",
                "DJANGO_LOG_LEVEL_CORE": "DEBUG",
                "DJANGO_DEBUG": "True",
                "DJANGO_USER_ACTIVATION_OVERRIDE_ADDRESSES": "",
                "DJANGO_USER_ACTIVATION_TOKEN_EXPIRY_S": ""
              },
              "frontendSecretsName": "galv-frontend-secrets",
              "frontendSecretsKeys": [],
              "backendSecretsName": "galv-backend-secrets",
              "backendSecretsKeys": [],
              "smtpSecretName": "",
              "monitorIntervalMinutes": 5,
              "frontendSubdomain": "${{ env.PROJECT_NAME }}-app",
              "backendSubdomain": "${{ env.PROJECT_NAME }}-api",
              "domainName": "${{ vars.CDK_CTX_DOMAIN_NAME }}",
              "isRoute53Domain": true,
              "enableContainerInsights": null
            }
          }
          EOF

      - name: Destroy stage backend
        run: |
          cd cdk
          cdk destroy \
            --force \
            galv-stage-BackendStack

      - name: Deploy the minimum compatible version
        if: inputs.min_compatible_version != ''
        run: |
          cd cdk
          cdk deploy \
            --require-approval never \
            --context backendVersion=${{ inputs.min_compatible_version }} \
            galv-stage-BackendStack

      - name: Deploy stage backend
        run: |
          cd cdk
          cdk deploy \
            --require-approval never \
            --context backendVersion=${{ github.ref_name }} \
            galv-stage-BackendStack

      - name: Get backend healthcheck content
        run: |
          curl -sS -o healthcheck.json \
            "https://${{ env.PROJECT_NAME }}-api.${{ env.DOMAIN_NAME }}/health/"
          cat healthcheck.json

      - name: Check healthcheck status ok
        run: |
          if ! jq -e '.status == "ok"' healthcheck.json; then
              echo "Backend healthcheck failed: $(jq -r '.status' healthcheck.json)"
              exit 1
          fi

      - name: "TODO: API checks"
        run: |
          echo "Any API checks should be added here."

      - name: Destroy stage backend
        run: |
          cd cdk
          cdk destroy \
            --force \
            galv-stage-BackendStack
